version: '3.8'

services:
  tomcat:
    image: myapp:latest
    container_name: myapp_container
    build: .
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:lts
    container_name: sonar
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    ports:
      - "5432:5432"
